### ISSUE TITLE
Ready to use version?

### ISSUE THREAD

**Issue by josephernest** [LukBukkit/chartist-plugin-tooltip#18]
Congrats for this project!
Is there a ready-to-use version, if possible on a CDN?

Something like:

    <script src="https://cdnjs.cloudflare.com/ajax/libs/chartist/0.11.4/chartist.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chartist-plugin-tooltip-updated/0.0.1/chartist-plugin-tooltip-updated.min.js"></script>

?

It would be great!

(I don't currently use npm or webpack for the minimalist project I'm working on, so a dist version would be useful)

**Comment by LukBukkit** [comment]
Hey,
thanks for reaching out.

You should be able to include the JavaScript and CSS files with unpkg:
```html
<link rel="stylesheet" href="https://unpkg.com/chartist-plugin-tooltips-updated@0.1.4/dist/chartist-plugin-tooltip.css">
<script src="https://unpkg.com/chartist-plugin-tooltips-updated@0.1.4/dist/chartist-plugin-tooltip.min.js"></script>
```

If it doesn't work, please let me know.

**Comment by LukBukkit** [comment]
I'm glad to hear that. If I've got some spare time, I'll incorporate your ideas into the repository 👍
