### ISSUE TITLE
Incorrect tooltip position

### ISSUE THREAD

**Issue by hakimio** [LukBukkit/chartist-plugin-tooltip#3]
Tooltip is positioned incorrectly. It's offset up and to the left:
![tooltip-bug](https://user-images.githubusercontent.com/768105/60254014-6ca54980-98cd-11e9-8569-5e85bea1deb5.png)

**Comment by hakimio** [comment]
Setting "appendToBody: true" seems to fix the offset. Anyway, "anchorToPoint" seems to be buggy as well, since it doesn't anchor to the same point and it's not centered horizontally.

**Comment by LukBukkit** [comment]
Thanks for reporting, I'm currently on vacation and I'm going to look into the problem when I'm home again.

**Comment by LukBukkit** [comment]
Hey,
I think I've found a solution for this issue.
Now the whole positioning of the tooltip is based on the `display:absolute` property.

You can grab a new version of this library from the [/dist/](https://github.com/LukBukkit/chartist-plugin-tooltip/tree/master/dist) folder.
It would be nice if you could try it out and if everything works correctly, I'll publish a new version of the plugin.

Thanks again!

**Comment by hakimio** [comment]
@LukBukkit Thanks, I'll check it out on Monday.

**Comment by hakimio** [comment]
@LukBukkit
While it seems to work as intended when "appendToBody" is set to "true", it's completely broken when "appendToBody" is false. Maybe you should remove that option and always append to body?

You can test the plugin yourself, by checking out [tooltip-plugin-usage-example](https://github.com/willsoto/ng-chartist/tree/tooltip-plugin-usage-example) branch from [willsoto/ng-chartist](https://github.com/willsoto/ng-chartist) repository. Tooltip plugin is used in the demo project's [TooltipChartComponent](https://github.com/willsoto/ng-chartist/blob/tooltip-plugin-usage-example/projects/ng-chartist-demo/src/app/components/tooltip-chart.component.ts).

Also, imho, it would be really nice if chart tooltips worked the same way they do on [HighCharts](https://www.highcharts.com/demo/line-basic) - you shouldn't have to hover exactly on the tiny point to see the tooltip.

Plus few other minor things:
* "anchorToPoint" should be true by default, since that's the default behavior most people would expect. [Is there actually any reason to have this config?]
* The tooltip is overlapping the line chart point after increasing the point size by modifying "ct-point" CSS class "stroke-width" property.

**Comment by LukBukkit** [comment]
Thanks for your ideas.

> While it seems to work as intended when "appendToBody" is set to "true", it's completely broken when "appendToBody" is false. Maybe you should remove that option and always append to body?  
You can test the plugin yourself, by checking out tooltip-plugin-usage-example branch from willsoto/ng-chartist repository. Tooltip plugin is used in the demo project's TooltipChartComponent.

Are you using the file(s) from the /dist/ folder? My latest fixes for this issue AREN'T published on npm, so that the version 0.0.21 still contains this issue.

> Also, imho, it would be really nice if chart tooltips worked the same way they do on HighCharts - you shouldn't have to hover exactly on the tiny point to see the tooltip.

Sorry, but I guess it would be a lot of work to implement a mode like this. I think they're showing the tooltip of the point which is the closest to the cursor.

> "anchorToPoint" should be true by default, since that's the default behavior most people would expect. [Is there actually any reason to have this config?]

I don't know, why the plugin was built this way, but I would keep the default option set to `false` to prevent surprises for those who don't have set the option.

> The tooltip is overlapping the line chart point after increasing the point size by modifying "ct-point" CSS class "stroke-width" property.

I guess it's planned this way, but isn't it possible to work with the z-index via css?

**Comment by hakimio** [comment]
> Are you using the file(s) from the /dist/ folder? My latest fixes for this issue AREN'T published on npm, so that the version 0.0.21 still contains this issue.

Yes, I am using the files from dist folder. As I mentioned before, you can also test the code I am using yourself by checking out  [tooltip-plugin-usage-example@willsoto/ng-chartist](https://github.com/willsoto/ng-chartist/tree/tooltip-plugin-usage-example).

> I guess it's planned this way, but isn't it possible to work with the z-index via css?

The tooltip is on top of the point but the tooltips arrow is positioned too low.

**Comment by LukBukkit** [comment]
Yeah I can confirm your problem and trying to fix it

**Comment by LukBukkit** [comment]
The problem should be fixed now. I also tested the fix with your example and it works (at least for me in Chrome and Firefox). You can find it, as always, in the dist folder.
But I can recommend to always use the option `appendToBody:true`, because it consumes a little less resources.

**Comment by hakimio** [comment]
@LukBukkit Looks good now. You can release a new version.

**Comment by LukBukkit** [comment]
A big thanks for reporting this issue and helping me testing. 

The new version `0.1.1` is now released: https://www.npmjs.com/package/chartist-plugin-tooltips-updated
