### ISSUE TITLE
list this plugin on chartist website?

### ISSUE THREAD

**Issue by titaniumbones** [LukBukkit/chartist-plugin-tooltip#5]
It would be great to update all the references on the chartist website to refer to this repo rather than the unmaintained original version. Have you considered a PR to the docs repo?

**Comment by LukBukkit** [comment]
That's a good idea. I try to submit a pull request this weekend.

**Comment by LukBukkit** [comment]
Sadly it isn't as easy as it seems. 
The website is built with a lot of outdated Grunt plugins (like a very old version of grunt-sass) and with bower, which is [deprecated](https://bower.io/blog/2017/how-to-migrate-away-from-bower/) since 2017, so it'll take more than expected.

**Comment by LukBukkit** [comment]
Here's the pull request on the chartist-js repository with the changes.
I'll close this pull request for now, because the work on my side is (hopefully) done. If you want, you can follow the other pull request.

Thanks for your hint 👍

**Comment by titaniumbones** [comment]
Thank you so much! Sorry I haven't had time to work on either of the issues I filed; I appreciate your help on this one!

On Dec. 25, 2019 5:03 p.m., Lukas <notifications@github.com> wrote:

Here's the pull request on the chartist-js repository with the changes.
I'll close this pull request for now, because the work on my side is (hopefully) done. If you want, you can follow the other pull request.

Thanks for your hint 👍
