### ISSUE TITLE
Not Working - Mouse Hover

### ISSUE THREAD

**Issue by uniquegamingoficial** [LukBukkit/chartist-plugin-tooltip#7]
Hi! After trying to install, I wasn't able to put it on work! 
May someone help me? 
I tried a simple version made in same page file and I'm not facing with the working version! 
There is no errors on console (Browser). 
All files are on webserver. 

Please Check screenshots: 
https://i.imgur.com/916jwPX.png
https://i.imgur.com/zLK6Otu.png
https://i.imgur.com/LPxLj70.png

Thank you all!

**Comment by LukBukkit** [comment]
Hello, I'll look into your issue as soon as possible (maybe today afternoon).

**Comment by uniquegamingoficial** [comment]
> Hello, I'll look into your issue as soon as possible (maybe today afternoon).

Sure, Thank you
